version: '3.3'
services:
    sshd:
        build: .
        ports:
            - "2222:22"
        environment:
            USERS: "davad"
            GITHUB: 1
            BITBUCKET: 1
            APP_PASSWORD: "12345"
